# Generated by Django 4.2.6 on 2023-10-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cod', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('qtd', models.IntegerField()),
                ('size', models.CharField(choices=[('1', 'P'), ('2', 'M'), ('3', 'G'), ('4', 'GG')], max_length=255)),
                ('discount', models.IntegerField()),
                ('created_at', models.DateField()),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
